app = "robo-voos-skyscanner-q2anvq"

[build]
  image = "python:3.11-slim"

[env]
  # Variáveis de ambiente podem ser adicionadas aqui
  # EXEMPLO: TELEGRAM_TOKEN = "seu_token_aqui"

[deploy]
  release_command = ""

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
